### ISSUE TITLE
Cannot read property 'zoomIn' of undefined

### ISSUE THREAD

**Issue by vagmen** [sylvaindubus/react-prismazoom#1]
Hi,I add a component 

```
<PrismaZoom ref="prizmaZoom">
   <img src={image}/>
</PrismaZoom>
```

After rendering `this.refs = {}`, so I can't use "this.refs.prismaZoom.zoomIn()"

**Comment by Smriti29** [comment]
Got any solution for this?

**Comment by KonstantinDinev** [comment]
I'm also experiencing the same issue using a Functional component with React.useRef hook

**Comment by sylvaindubus** [comment]
I think you made a typo in your `ref` prop. You put "prizmaZoom" (with a "z") instead of "prismaZoom".
