### ISSUE TITLE
Mobile DoubleClick Zoom not Working...

### ISSUE THREAD

**Issue by vinothkumarb** [sylvaindubus/react-prismazoom#11]
Hi ,
I am removed eventpreventDefault in handleTouchStop because i want to click link  So DoubleClick Zoom not Working..

Thanks in advance..

**Comment by sylvaindubus** [comment]
Hi,

I don't really understand your point. `handleTouchStop` does not call `event.preventDefault`.
Could you explain more precisely or show the problem somewhere?

**Comment by sylvaindubus** [comment]
I'm closing it for now, feel free to open it again with some more info!
