### ISSUE TITLE
When using mouse wheel zoom getting "Unable to preventDefault inside passive event listener due to target being treated as passive"

### ISSUE THREAD

**Issue by tmaxim-gpsw** [sylvaindubus/react-prismazoom#12]
Full error shown in Chrome 87.0.4280.67 
```
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312
```

My React component:
```
function Photo({ imageData }) {
  return (
    <PrismaZoom>
      <img src={imageData} />
    </PrismaZoom>
  );
}
```
The link in the error takes me to a general issues page... but seems to be a Chrome issue, not getting it in Safari.

**Comment by harsimerkaur** [comment]
I am also getting this error.

**Comment by tmaxim-gpsw** [comment]
Hi, yes, I did some debugging and we can add the passive: false when we add the listener, but we will have to do it in componentDidMount the old fashioned way - addEventListener and move away from adding the 'SyntheticEvent' onWheel.
Will have a PR soon.

**Comment by sylvaindubus** [comment]
Thanks for the report!

This bug is now fixed with the new major version (2.0.0).

**Comment by pantchox** [comment]
Hi I am still getting this error on v2.0.3

**Comment by pantchox** [comment]
I get this error on v2.0.3 when the browser is in mobile emulation when I am zooming and then dragging the image to pan.
I assume it is related to touch events.
