### ISSUE TITLE
Support for embedding inside container

### ISSUE THREAD

**Issue by UlyssesInvictus** [sylvaindubus/react-prismazoom#14]
It looks as if the calculation for the right limit uses the document boundaries:

```
    // Get horizontal limits using specified horizontal boundaries
    const [leftLimit, rightLimit] = [
      leftBoundary,
      document.body.clientWidth - rightBoundary
    ]
```

Is it possible to use the bounding rect instead? It looks like there's already some kind of support for container bounds instead:

```
    // Get container and container's parent coordinates
    const rect = this.ref.current.getBoundingClientRect()
    const parentRect = this.ref.current.parentNode.getBoundingClientRect()
```

Is it possible to just use `parentRect` instead of `document.body`?

**Comment by sylvaindubus** [comment]
Hey,

It sounds a good idea! In fact, i'm not sure boundaries props are still required.

I made a release candidate version which uses the wrapper dimensions instead: 2.0.1-rc0. Feel free to try out and let me now if there is any bug. ;)

**Comment by sylvaindubus** [comment]
Change deployed, feel free to open it again if necessary!
