### ISSUE TITLE
Scroll in PrizmaZoom

### ISSUE THREAD

**Issue by nikita-lazarev-up** [sylvaindubus/react-prismazoom#18]
Hi everyone! I have some problem: then I use PrizmaZoom for my component I cannot use scroll for my pictures in component. I have pictures that are mapping one by one to column (I use flex-direction  :  column, then my flag "verticalPages" is true). The simplified code is:
<PrismaZoom
        maxZoom={1.7}
        scrollVelocity={0}
        className="h-full"
      >
         pages.map((page, pageIndex) => (
                    <div key={page.Id} className="relative">
                      <img
                        className={`h-full w-full ${
                          verticalPages ? "" : "border-l-2"
                        } border-black`}
                        ref={(el) => {
                          imageRef.current = {
                            ...imageRef?.current,
                            [pageIndex]: el,
                          };
                        }}
                        src={`https:${page.BasePath}${
                          isSmall.width <= 768 ? 4 : 6
                        }/${page.FileName}`}
                        alt="page"
                      />
      </PrismaZoom>
      
      And If I take away <PrismaZoom> - I can scroll my pages up and down, but with One - it impossible((( or may be I do something wrong? In principle, does it possible to use scroll and zoom together?

**Comment by sylvaindubus** [comment]
Hello!

Currently, this is not possible to scroll on the page and zoom at the same time. Or even preventing zoom to scroll instead. If you want to contribute on this point, you are welcome. :)
The `handleMouseWheel` prevents the default scroll behavior, you could either add a props to prevent zooming by scrolling, or just add a condition on this line when you can't zoom in or out anymore.
