### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by justsolarry** [sylvaindubus/react-prismazoom#22]
## Problem
I've attached the Sentry error below and all extra information
![image](https://user-images.githubusercontent.com/21080305/124192881-4ae78a00-dac6-11eb-89d6-9188507efd85.png)
![image](https://user-images.githubusercontent.com/21080305/124192942-5c309680-dac6-11eb-8548-3fdd7dcca9e3.png)
![image](https://user-images.githubusercontent.com/21080305/124192962-6357a480-dac6-11eb-8a56-91684b801956.png)

## package versions
"react-prismazoom": "^2.0.1"
"react": "^17.0.2"
"react-scripts": "^4.0.3"
"node": ">=10.0.0"

## Implementation 
![carbon](https://user-images.githubusercontent.com/21080305/124193349-f5f84380-dac6-11eb-932c-c765603b4ad2.png)

I haven't been able to replicate and I wonder if you have any ideas?

Thanks!

**Comment by sylvaindubus** [comment]
It should be fixed by 2.0.3.
Wasn't able to replicate either, but it think it was occurring when the component was unmounted but still finishing a move.
