### ISSUE TITLE
Double tap on iOS Safari Bug

### ISSUE THREAD

**Issue by justsolarry** [sylvaindubus/react-prismazoom#23]
## Problem
Double tapping on ios safari doesn't work. It zooms in for a moment but zooms back out. 
Single tap doesn't do anything. 
Pan and zoom still works.
https://user-images.githubusercontent.com/21080305/124193688-9484a480-dac7-11eb-9a81-ad00fc951272.MP4

## Package versions
"react-prismazoom": "^2.0.1"
"react": "^17.0.2"
"react-scripts": "^4.0.3"
"node": ">=10.0.0"

## IOS version
IOS software 14.6

**Comment by sylvaindubus** [comment]
It should be fixed with 2.0.3, thanks for the feedback!
