### ISSUE TITLE
Pinch doesn't work after version 2.0.0

### ISSUE THREAD

**Issue by danielllk** [sylvaindubus/react-prismazoom#27]
Hi! Thanks for the plugin!

There is an issue after version 2.0.0. Basically, pinch and touch events don't work on desktop ( normal mode ). They only work with developer tools "on". I didn't find why, but after downgrade to version 2.0.0. everything started to work. But as version 2.0.0 has a different approach, I used negative boundaries to fix the "off-screen issues". Still, if you double click on edge of the screen very fast it will go "off the screen". 

By the way, your demo is working because it's built on an older version of the plugin.

P.S. Sorry, I don't have a fast solution for this issue. I just played with negative boundaries and it seems to work. 

I hope, I helped someone

Regards

**Comment by sylvaindubus** [comment]
Hi!

Sorry for the delay.
I can't reproduce these issues, even after upgrading the demo to the latest version. If you still facing these problems, could you provide some info about your environment: operating system, browser, browser version?
