### ISSUE TITLE
Lot's of `Unable to preventDefault inside passive event listener invocation` errors

### ISSUE THREAD

**Issue by fkrauthan** [sylvaindubus/react-prismazoom#28]
I've noticed that currently the code throws a lot of

```
Unable to preventDefault inside passive event listener invocation
```

errors inside the touch even listeners. Everything seems to be working fine but maybe you can take a look at it?

**Comment by sylvaindubus** [comment]
Hi,

I've noticed these errors a long time ago, but I can't see them anymore. In which environment are you getting these? Are you using the last version?

**Comment by fkrauthan** [comment]
I am using version `2.0.3` so the current latest version. And it is as part of a create react app application:

- `react-scripts` has version `4.0.3`
- `@craco/craco` has version `6.4.0`
- `react` has version `17.0.2`

Not sure if any other dependency might be relevant?

**Comment by sylvaindubus** [comment]
Damn, I can't see these errors. I've also tried on multiple browsers.
Do you bind extra event listeners? Could you show the problem on https://codesandbox.io?

**Comment by fkrauthan** [comment]
Ok so the warning does not show up regular but if you open the device toolbar (at least on Chrome) and then use your mouse to drag around. Then all this warnings show up.

You can also see that on this codesandbox: https://codesandbox.io/s/prisma-zoom-issue-3m1fv?file=/src/App.js 

I believe this link works as well: https://3m1fv.csb.app/


To reproduce just do this steps:

1. Open the app in a development build
2. Open Chrome Developer Tools
3. Turn on Device Emulator and pick a phone device
4. Zoom in and then click and drag to move the view
5. Check the Console and see all the warnings posted

**Comment by fkrauthan** [comment]
Sorry for the double post. But I am wondering if the issue is that mobile devices (and I assume the emulator as well) triggers touch AND click events in case of touch and that this is causing some type of conflicts in event processing?

**Comment by sylvaindubus** [comment]
Thanks for the additional info. I've missed the point when you talked about touch events. I can easily reproduce this problem.

I'll fix it next week, it seems to work by changing the way events are binded to the component. However, mouse and touch events are already separated, it can't be the problem. I'm guessing it's about how React manages active/passive events.

**Comment by sylvaindubus** [comment]
Hello,

I've published a release candidate version which should prevent this warning, but I had to change how events are binded. Could you try installing version 2.1.1-rc0 and tell me if everything is working?

Thanks!

**Comment by fkrauthan** [comment]
That new version seem to work fine. Except when using Developer Tools Emulator. In that case I don't seem to be able to move the map anymore. But on a real device and on regular Desktop mode it seem to be working.

**Comment by fkrauthan** [comment]
The only thing (but this might be better an additional ticket). I have some overlay DIV's with a tooltip. They work fine on desktop but I assume because you catch all click/touch events the tooltip is never triggered on mobile devices.

**Comment by sylvaindubus** [comment]
Hey! About your first message, do you mean it isn't working anymore on a real device? It seem to work when I tried it (latest Chrome, Android 11).

**Comment by fkrauthan** [comment]
Hmm no it was working on a real device but not when emulating a mobile device inside chrome developer tools. But not sure if that was a onetime glitch or something.

**Comment by sylvaindubus** [comment]
Okay, feel free to open it again if you encounter this problem again (but quite not sure this glitch was linked to this issue).
