### ISSUE TITLE
Option to disable panning?

### ISSUE THREAD

**Issue by joshuacerdenia** [sylvaindubus/react-prismazoom#29]
Love this package, very easy to use.

Would it be possible to add a prop to disable panning or dragging, or otherwise disable the component completely while frozen at a specific zoom value? I'd like to be able to zoom at a particular point in an image, and have the mouse free to perform other operations on the image while frozen there.

Hope you'll consider it, and thanks for the great package!

**Comment by sylvaindubus** [comment]
Hey, thanks for your compliments!
I've added a "locked" prop on the new version (2.1.0).

**Comment by joshuacerdenia** [comment]
Works great. Thanks for the quick update!
