### ISSUE TITLE
Is it possible to not have the zoom affect the whole page

### ISSUE THREAD

**Issue by parvussaku** [sylvaindubus/react-prismazoom#36]
As stated, I would like to have a container for the image and have the zoom only affect that part of the webpage (leaving rest of the page unaffected). At the moment when you zoom in it zooms the whole webpage in hiding crucial parts of the page. Is this package not meant for something like this or is it somehow possible?

Thanks in advance!

**Comment by artemijspavlovs** [comment]
@parvussaku how did you solve this?

**Comment by parvussaku** [comment]
> @parvussaku how did you solve this?

Sorry it has been a while for me, but I vaguely remember it being tag positioning on my part. Ie. having the <PrismaZoom>tags encircle the body of the page aswell or something like that.
