### ISSUE TITLE
Pan does not work with React 18

### ISSUE THREAD

**Issue by empawlo** [sylvaindubus/react-prismazoom#43]
Hello all

just upgraded to React 18.1.0 and have noticed that the **pan no longer works**. Please test it yourself - there are also problems on mobile devices. I'll downgrade to React 17 until a solution was found. I am looking forward to it...

**Comment by brianlovin** [comment]
Can confirm, the pan doesn't seem to work in `react@18.0.0` — will keep an eye out here, and downgrade in the meantime 😊

**Comment by sylvaindubus** [comment]
Hi,

My bad, I think it was still using React 17 under the hood when I've tested it.

It should be fixed in 3.0.3, let me know if it's working back so I can close this. ;)

**Comment by brianlovin** [comment]
Working for me @sylvaindubus — apologies for the slow reply here!

I can stub something out in the meantime, but a `@types/react-prismazoom` would be awesome for TypeScript users (maybe a lot of people with Next.js?). Anyways, I'm sure it's not a priority, but wanted to mention it 😊 

Thank you!

**Comment by sylvaindubus** [comment]
Glad to hear it's now working correctly!

Btw, I would love to transform all the codebase in Typescript, it's even at the top of the todo list (in the Contribution part of the readme), unfortunately it takes some time and I don't have enough of it for now. If you feel motivated, you are most welcome. 😉
