### ISSUE TITLE
Are there plans for using Typescript?

### ISSUE THREAD

**Issue by erickriva** [sylvaindubus/react-prismazoom#50]
This is a must-have for me, maybe is for someone else too.
If needed, I can send a PR.

**Comment by erickriva** [comment]
Okay, I admit. I haven't seen README prior to create this issue.
Sorry 😅

Which approach do you think it's the best for this package?
Just a `d.ts` file? Fully typed library?

**Comment by sylvaindubus** [comment]
No problem!
Fortunately, someone started to work on that by writing a `d.ts` file, it's a good first step prior to a full conversion: https://github.com/sylvaindubus/react-prismazoom/pull/51

**Comment by sylvaindubus** [comment]
I've just commented on your MR, but it's really great, thanks again. 🙌

**Comment by erickriva** [comment]
Solved by #57
