### ISSUE TITLE
Demo images are being cropped

### ISSUE THREAD

**Issue by smaydew** [sylvaindubus/react-prismazoom#53]
In the demo App.css entry **.App-image** **_background-size: cover_**  prevents the entire image from being displayed. Setting it to **_background-size: contain_** will display the complete image.

Whether or not this is an issue, I'll leave that to the maintainer(s), just an observation.

**Comment by sylvaindubus** [comment]
Thanks for pointing it out. I've set it on purpose to always have the image at full-size, whether the device size. It makes things convenient on mobile, even if it doesn't fully respect these paintings. But the best solution would be to use different images on smaller screens.
