### ISSUE TITLE
Zoom using double-click ignoring position

### ISSUE THREAD

**Issue by elbotho** [sylvaindubus/react-prismazoom#63]
Using double-click the image zooms in to the center and ignores the event position. 
I expected it to zoom in on the position I clicked.

Tested in current Chrome and Firefox.

**Comment by elbotho** [comment]
Not sure why. Code looks like it should do what I want it to do on first glance ^^
https://github.com/sylvaindubus/react-prismazoom/blob/master/src/index.tsx#L386

**Comment by sylvaindubus** [comment]
Thanks for spotting it! It is now fixed in `3.2.1`. :)
This was a little regression with the big refactor that happened a few weeks ago.

**Comment by elbotho** [comment]
Thank you!
